language: node_js
node_js: '8'

env: DB=mysql
script:
    - pm2 start app.js
    #- curl 127.0.0.1:3000
    - pm2 log
notifications:
    email:
        recipients: gytlinux@163.com
        on_failure: always

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
    - export PATH="$HOME/.yarn/bin/:$PATH"
    - yarn global add pm2
    - mysql -uroot -e "use mysql;update user set password=PASSWORD('gytlinux') where User='root';"
    - cp example.env .env
