language: node_js
node_js: '8'

services: mysql
install: yarn
script:
    - pm2 start app.js 
    - sleep 3
    - curl localhost:3000/code
notifications:
    email:
        recipients: 
            - gytlinux@163.com
            - gytlinux@139.com
        on_failure: always

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
    - export PATH="$HOME/.yarn/bin/:$PATH"
    - yarn global add pm2
    - cp example.env .env
